### ISSUE TITLE
Rogue print statement in vcf2variants

### ISSUE THREAD

**Issue by rhpvorderman** [varda/varda2_preprocessing#9]
https://github.com/varda/varda2_preprocessing/blob/9ab78b8b00ef12760ddf3476256366ea11097f58/vcf2variants/vcf2variants/__init__.py#L54

Since the output is also created with a print statement, this rogue statement creates a non-csv line in the csv.

**Comment by marksantcroos** [comment]
Oops, tests don't cover the CLI path.
I've pushed an update to PyPi, hopefully the container is automagically bumped soon.

**Comment by rhpvorderman** [comment]
That was quick! Thanks!

**Comment by marksantcroos** [comment]
New container at `docker://quay.io/biocontainers/vcf2variants:1.3--pyhdfd78af_0`.

**Comment by marksantcroos** [comment]
I'll close this one once you can confirm it works.

**Comment by rhpvorderman** [comment]
It works!
